### PR TITLE
support Laravel 7

### PR DESCRIPTION
**Pull request by stevethomas**
Also fixed a double pipe typo.

### CODE REVIEW

**Comment by DivineOmega** [comment]
Hi @stevethomas. Thanks for the PR.  :+1: 

The double pipe is not actually a typo.

> A double pipe (||) will be treated as a logical OR.

Source: https://getcomposer.org/doc/articles/versions.md#version-range

**Comment by stevethomas** [comment]
oh nice, didn't know `||` was a thing!

Is there a specific reason for || in this case?

**Comment by DivineOmega** [comment]
Not specifically. I tend to use `||`. I've not noticed `|` documented for Composer.

**Comment by stevethomas** [comment]
done

**Comment by DivineOmega** [comment]
Laravel 7.0 support has been added as part of #28

**Pull request closed without merging**
